### ISSUE TITLE
Supporting multiple gazelle sites?

### ISSUE THREAD

**Issue by philipbjorge** [Gwindow/WhatAndroid#32]
Are you open to the idea of switching between multiple gazelle sites using an some settings and a menu similar to below?

![](http://cdn1.androidhive.info/wp-content/uploads/2013/11/android-action-bar-adding-spinner-navigation.png?f8d261)

Or would you prefer that separate gazelle sites maintain their own fork of WhatAndroid?

**Comment by Twinklebear** [comment]
It'd be a lot easier for me if other sites maintained their own fork of the app as I don't have enough time to maintain more than one. The WhatAPI library and app code should provide an ok starting point and are both openly licensed, forking is also probably a cleaner approach if other sites have tweaks to the API or different layouts/information they'd want to display.

**Comment by philipbjorge** [comment]
Cool -- Works for me.
Thanks
