### ISSUE TITLE
Download button title 'Save to phone' should be changed

### ISSUE THREAD

**Issue by DmitrySandalov** [Gwindow/WhatAndroid#35]
The title 'Save to phone' does not make sense if used on tablet, HDMI stick, etc.

New title could be like 'Save to device' or smth like that.

![tmp_31245-screenshot_2015-06-29-12-14-14-881647645](https://cloud.githubusercontent.com/assets/1167276/8404924/955f9c9c-1e59-11e5-8e70-bffe771b4c8b.png)

**Comment by Twinklebear** [comment]
Fixed by #36, thanks!
